__target__: EnhancedVelocityModuleCDRepulsion
frame_knn_list: [16, 32, 48]
num_train_points: 192
feat_embedding_dim: 384
decoder_hidden_dim: 128
dsm_sigma: 0.01
cd_weight: 0.03
repulsion_weight: 0.0
displacement_weight: 0.0003
num_cd_points: 128
centroid_weight: 0.02
covariance_weight: 0.01