mode: predict
debug: False
load_ckpt: experiments/vm/checkpoint_best_manual.pkl

components:
  data: predict
  transform: predict 
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: results
  save_name: denoised