mode: predict
debug: False
load_ckpt: experiments/enhanced_vm/checkpoint_99.pkl

components:
  data: predict_train
  transform: vm
  system: enhanced_vm
  model: enhanced_vm

writer:
  __target__: vm
  save_dir: results/train_enhanced_eval
  save_name: denoised