mode: train
debug: False

components:
  data: train_enhanced
  transform: vm
  system: enhanced_vm
  model: enhanced_vm

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.00001

trainer:
  epochs: 100