mode: train
debug: False

components:
  data: train_enhanced_v2_workers4
  transform: vm_v5_conservative_refine
  system: enhanced_vm_v7_geom_loss
  model: enhanced_vm_v7_geom_loss

load_ckpt: experiments/enhanced_vm_v5_conservative_refine/checkpoint_best_screened.pkl

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.000001

trainer:
  epochs: 10